stages:
  - build

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /env/
      variables:
        IS_FEATURE_BRANCH: "true"

ui-image:
  stage: build
  rules:
    - if: $IS_FEATURE_BRANCH = "true" 
  script:
    - echo "building boluswizard/ui image"
    - docker build -t registry.nated.io/phosphorusmyesophagus/boluswizard/ui:$CI_COMMIT_SHORT_SHA . -f ui.dockerfile
    - docker push registry.nated.io/phosphorusmyesophagus/boluswizard/ui:$CI_COMMIT_SHORT_SHA
    - echo "image boluswizard/ui was built succesfully."

api-image:
  stage: build
  rules:
    - if: $IS_FEATURE_BRANCH = "true"
  script:
    - echo "building boluswizard/api image"
    - docker build -t registry.nated.io/phosphorusmyesophagus/boluswizard/api:$CI_COMMIT_SHORT_SHA . -f api.dockerfile
    - docker push registry.nated.io/phosphorusmyesophagus/boluswizard/api:$CI_COMMIT_SHORT_SHA
    - echo "image boluswizard/api was built succesfully."
