stages:
  - ui
  - api

api-image:
  stage: api
  script:
    - echo "building boluswizard/api image"
    - export PAT=JscJAxSWqyqCQtPYhq_3
    - echo $PAT | docker login registry.nated.io -u nate --password-stdin
    - docker build -t registry.nated.io/phosphorusmyesophagus/boluswizard/api:v$(cat ./VERSION) ./api -f ./api/api.dockerfile
    - docker push registry.nated.io/phosphorusmyesophagus/boluswizard/api:v$(cat ./VERSION)
    - echo "image boluswizard/api was built succesfully."
ui-image:
  stage: ui
  script:
    - echo "building boluswizard/ui image"
    - export PAT=JscJAxSWqyqCQtPYhq_3
    - echo $PAT | docker login registry.nated.io -u nate --password-stdin
    - docker build -t registry.nated.io/phosphorusmyesophagus/boluswizard/ui:v$(cat ./VERSION) ./ui -f ./ui/ui.dockerfile
    - docker push registry.nated.io/phosphorusmyesophagus/boluswizard/ui:v$(cat ./VERSION)
    - echo "image boluswizard/ui was built succesfully."