stages:
  - ui
  - api
  - version

api-image:
  stage: api
  script:
    - echo "building boluswizard/api image"
    - export PAT=JscJAxSWqyqCQtPYhq_3
    - echo $PAT | docker login registry.nated.io -u nate --password-stdin
    - docker build -t registry.nated.io/phosphorusmyesophagus/boluswizard/api:v$CI_PIPELINE_ID ./api -f ./api/api.dockerfile
    - docker push registry.nated.io/phosphorusmyesophagus/boluswizard/api:v$CI_PIPELINE_ID
    - echo "image boluswizard/api was built succesfully."
ui-image:
  stage: ui
  script:
    - echo "building boluswizard/ui image"
    - export PAT=JscJAxSWqyqCQtPYhq_3
    - echo $PAT | docker login registry.nated.io -u nate --password-stdin
    - docker build -t registry.nated.io/phosphorusmyesophagus/boluswizard/ui:v$CI_PIPELINE_ID ./ui -f ./ui/ui.dockerfile
    - docker push registry.nated.io/phosphorusmyesophagus/boluswizard/ui:v$CI_PIPELINE_ID
    - echo "image boluswizard/ui was built succesfully."
version:
  stage: version
  script:
    - echo "Increment version"
    - export version=$CI_PIPELINE_ID | sed -i "1s/.*/$version/" VERSION


