// Code generated by go-swagger; DO NOT EDIT.

// Package restapi BolusWizard
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
