apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-boluswizard
spec:
  rules:
  - host: api.boluswizard.io
    http:
      paths:
      - backend:
          service:
            name: api-boluswizard
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.boluswizard.io
    secretName: boluswizard-tls
---
apiVersion: v1
kind: Service
metadata:
  name: api-boluswizard
spec:
  type: ClusterIP
  selector:
    app: api-boluswizard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-boluswizard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-boluswizard
  template:
    metadata:
      labels:
        app: api-boluswizard
    spec:
      imagePullSecrets:
      - name: boluswizard-registry
      containers:
        - name: api-boluswizard
          image: registry.nated.io/phosphorusmyesophagus/boluswizard/api:v1.5 # change this to right registry
          imagePullPolicy: Always
          env:
          - name: REDIS_HOSTNAME
            value: "redis.bwdev.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            value: "RU2DLZhTIa9z_FS9HW+*L5px$GeR!A6&"
          ports:
            - containerPort: 81
