apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-boluswizard
spec:
  rules:
  - host: {{ .Values.API_FQDN }}
    http:
      paths:
      - backend:
          service:
            name: api-boluswizard
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.BW_FQDN }}
    secretName: boluswizard-tls
---
apiVersion: v1
kind: Service
metadata:
  name: api-boluswizard
spec:
  type: ClusterIP
  selector:
    app: api-boluswizard
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.API_PORT }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-boluswizard
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-boluswizard
  template:
    metadata:
      labels:
        app: api-boluswizard
    spec:
      imagePullSecrets:
      - name: boluswizard-registry
      containers:
        - name: api-boluswizard
          image: registry.nated.io/phosphorusmyesophagus/boluswizard/api:v{{ .Values.VERSION }} # change this in pipeline
          imagePullPolicy: Always
          env:
          - name: REDIS_HOSTNAME
            value: {{ .Values.REDIS_HOSTNAME }}
          - name: REDIS_PORT
            value: {{ .Values.REDIS_PORT }}
          - name: REDIS_PASSWORD
            value: {{ .Values.REDIS_PASSWORD }}
          ports:
            - containerPort: {{ .Values.API_PORT }}
