apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boluswizard
spec:
  tls:
  - hosts:
      - dev.boluswizard.ca
    secretName: boluswizard-tls
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: boluswizard

---
apiVersion: v1
kind: Service
metadata:
  name: boluswizard
spec:
  type: ClusterIP
  selector:
    app: boluswizard
  ports:
    - protocol: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boluswizard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: boluswizard
  template:
    metadata:
      labels:
        app: boluswizard
    spec:
      imagePullSecrets:
      - name: boluswizard-registry
      containers:
        - name: boluswizard
          image: registry.nated.io/phosphorusmyesophagus/boluswizard/ui:v1.4 # change this to right registry
          ports:
            - containerPort: 80
          env:
          - name: API_HOSTNAME
            value: "https://devapi.boluswizard.io/"
          - name: API_PORT
            value: "81"

