apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boluswizard
  namespace: {{ .Values.NAMESPACE }}
spec:
  rules:
  - host: {{ .Values.BW_FQDN }}
    http:
      paths:
      - backend:
          service:
            name: boluswizard
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.BW_FQDN }}
    secretName: boluswizard-tls
---
apiVersion: v1
kind: Service
metadata:
  name: boluswizard
  namespace: {{ .Values.NAMESPACE }}
spec:
  type: ClusterIP
  selector:
    app: boluswizard
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.UI_EXTERNAL_PORT }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boluswizard
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: boluswizard
  template:
    metadata:
      labels:
        app: boluswizard
    spec:
      imagePullSecrets:
      - name: boluswizard-registry
      containers:
        - name: boluswizard
          image: ghcr.io/delduked/boluswizard/ui:v{{ .Values.VERSION }} # change this in pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.UI_EXTERNAL_PORT }}
          env:
          - name: API_HOSTNAME
            value: {{ .Values.API_HOSTNAME }}
          - name: API_PORT
            value: {{ .Values.UI_EXTERNAL_PORT }}

