apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boluswizard
spec:
  rules:
  - host: dev.boluswizard.io
    http:
      paths:
      - backend:
          service:
            name: boluswizard
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - dev.boluswizard.io
    secretName: boluswizard-tls
---
apiVersion: v1
kind: Service
metadata:
  name: boluswizard
spec:
  type: ClusterIP
  selector:
    app: boluswizard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boluswizard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: boluswizard
  template:
    metadata:
      labels:
        app: boluswizard
    spec:
      imagePullSecrets:
      - name: boluswizard-registry
      containers:
        - name: boluswizard
          image: registry.nated.io/phosphorusmyesophagus/boluswizard/ui:v1.5 # change this to right registry
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: API_HOSTNAME
            value: "https://devapi.boluswizard.io/"
          - name: API_PORT
            value: "80"

