# public prod setup
ENVIRONMENT: "prod"
# api access to redis env
REDIS_HOSTNAME: "redis.bw.svc.cluster.local"
REDIS_PASSWORD: "RU2DLZhTIa9z_FS9HW+*L5px$GeR!A6&"
REDIS_PORT: "6379"
# ui access to api env
API_HOSTNAME: "https://api.boluswizard.io/"
API_PORT: "81"
# public access to ui
UI_EXTERNAL_PORT: "80"
UI_HOSTNAME: "ui"
# helm
NAMESPACE: "bw"
VERSION: "1.5.0"
BW_FQDN: boluswizard.io
API_FQDN: api.boluswizard.io
TLS_SECRET: boluswizard.io
PV_PATH: "/storage/bw-prod-pv"