// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"boluswizard/models"
)

// CorrectionRangeHandlerFunc turns a function with the right signature into a correction range handler
type CorrectionRangeHandlerFunc func(CorrectionRangeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CorrectionRangeHandlerFunc) Handle(params CorrectionRangeParams) middleware.Responder {
	return fn(params)
}

// CorrectionRangeHandler interface for that can handle valid correction range params
type CorrectionRangeHandler interface {
	Handle(CorrectionRangeParams) middleware.Responder
}

// NewCorrectionRange creates a new http.Handler for the correction range operation
func NewCorrectionRange(ctx *middleware.Context, handler CorrectionRangeHandler) *CorrectionRange {
	return &CorrectionRange{Context: ctx, Handler: handler}
}

/*
	CorrectionRange swagger:route GET /wizard/CorrectionRange correctionRange

get correction range
*/
type CorrectionRange struct {
	Context *middleware.Context
	Handler CorrectionRangeHandler
}

func (o *CorrectionRange) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCorrectionRangeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CorrectionRangeOKBody correction range o k body
//
// swagger:model CorrectionRangeOKBody
type CorrectionRangeOKBody struct {

	// data
	Data []*models.Correction `json:"Data"`

	// error
	Error interface{} `json:"Error,omitempty"`

	// status
	Status int64 `json:"Status,omitempty"`
}

// Validate validates this correction range o k body
func (o *CorrectionRangeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CorrectionRangeOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("correctionRangeOK" + "." + "Data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("correctionRangeOK" + "." + "Data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this correction range o k body based on the context it is used
func (o *CorrectionRangeOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CorrectionRangeOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("correctionRangeOK" + "." + "Data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("correctionRangeOK" + "." + "Data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *CorrectionRangeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CorrectionRangeOKBody) UnmarshalBinary(b []byte) error {
	var res CorrectionRangeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
