// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// CreateTargetsOKCode is the HTTP code returned for type CreateTargetsOK
const CreateTargetsOKCode int = 200

/*
CreateTargetsOK Successful operation

swagger:response createTargetsOK
*/
type CreateTargetsOK struct {

	/*
	  In: Body
	*/
	Payload *CreateTargetsOKBody `json:"body,omitempty"`
}

// NewCreateTargetsOK creates CreateTargetsOK with default headers values
func NewCreateTargetsOK() *CreateTargetsOK {

	return &CreateTargetsOK{}
}

// WithPayload adds the payload to the create targets o k response
func (o *CreateTargetsOK) WithPayload(payload *CreateTargetsOKBody) *CreateTargetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create targets o k response
func (o *CreateTargetsOK) SetPayload(payload *CreateTargetsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTargetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CreateTargetsDefault Unsuccessful operation

swagger:response createTargetsDefault
*/
type CreateTargetsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreateTargetsDefault creates CreateTargetsDefault with default headers values
func NewCreateTargetsDefault(code int) *CreateTargetsDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateTargetsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create targets default response
func (o *CreateTargetsDefault) WithStatusCode(code int) *CreateTargetsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create targets default response
func (o *CreateTargetsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create targets default response
func (o *CreateTargetsDefault) WithPayload(payload *models.Response) *CreateTargetsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create targets default response
func (o *CreateTargetsDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTargetsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
