// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateTargetsHandlerFunc turns a function with the right signature into a create targets handler
type CreateTargetsHandlerFunc func(CreateTargetsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateTargetsHandlerFunc) Handle(params CreateTargetsParams) middleware.Responder {
	return fn(params)
}

// CreateTargetsHandler interface for that can handle valid create targets params
type CreateTargetsHandler interface {
	Handle(CreateTargetsParams) middleware.Responder
}

// NewCreateTargets creates a new http.Handler for the create targets operation
func NewCreateTargets(ctx *middleware.Context, handler CreateTargetsHandler) *CreateTargets {
	return &CreateTargets{Context: ctx, Handler: handler}
}

/*
	CreateTargets swagger:route POST /Targets createTargets

Create Target Ratios
*/
type CreateTargets struct {
	Context *middleware.Context
	Handler CreateTargetsHandler
}

func (o *CreateTargets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateTargetsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateTargetsOKBody create targets o k body
//
// swagger:model CreateTargetsOKBody
type CreateTargetsOKBody struct {

	// data
	Data interface{} `json:"Data,omitempty"`

	// error
	Error interface{} `json:"Error,omitempty"`

	// status
	Status int64 `json:"Status,omitempty"`
}

// Validate validates this create targets o k body
func (o *CreateTargetsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create targets o k body based on context it is used
func (o *CreateTargetsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateTargetsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTargetsOKBody) UnmarshalBinary(b []byte) error {
	var res CreateTargetsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
