// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// CreateRatiosOKCode is the HTTP code returned for type CreateRatiosOK
const CreateRatiosOKCode int = 200

/*
CreateRatiosOK Successful operation

swagger:response createRatiosOK
*/
type CreateRatiosOK struct {

	/*
	  In: Body
	*/
	Payload *CreateRatiosOKBody `json:"body,omitempty"`
}

// NewCreateRatiosOK creates CreateRatiosOK with default headers values
func NewCreateRatiosOK() *CreateRatiosOK {

	return &CreateRatiosOK{}
}

// WithPayload adds the payload to the create ratios o k response
func (o *CreateRatiosOK) WithPayload(payload *CreateRatiosOKBody) *CreateRatiosOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create ratios o k response
func (o *CreateRatiosOK) SetPayload(payload *CreateRatiosOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRatiosOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CreateRatiosDefault Unsuccessful operation

swagger:response createRatiosDefault
*/
type CreateRatiosDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreateRatiosDefault creates CreateRatiosDefault with default headers values
func NewCreateRatiosDefault(code int) *CreateRatiosDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateRatiosDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create ratios default response
func (o *CreateRatiosDefault) WithStatusCode(code int) *CreateRatiosDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create ratios default response
func (o *CreateRatiosDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create ratios default response
func (o *CreateRatiosDefault) WithPayload(payload *models.Response) *CreateRatiosDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create ratios default response
func (o *CreateRatiosDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRatiosDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
