// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// CreateDurationOKCode is the HTTP code returned for type CreateDurationOK
const CreateDurationOKCode int = 200

/*
CreateDurationOK Successful operation

swagger:response createDurationOK
*/
type CreateDurationOK struct {

	/*
	  In: Body
	*/
	Payload *CreateDurationOKBody `json:"body,omitempty"`
}

// NewCreateDurationOK creates CreateDurationOK with default headers values
func NewCreateDurationOK() *CreateDurationOK {

	return &CreateDurationOK{}
}

// WithPayload adds the payload to the create duration o k response
func (o *CreateDurationOK) WithPayload(payload *CreateDurationOKBody) *CreateDurationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create duration o k response
func (o *CreateDurationOK) SetPayload(payload *CreateDurationOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDurationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CreateDurationDefault Unsuccessful operation

swagger:response createDurationDefault
*/
type CreateDurationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreateDurationDefault creates CreateDurationDefault with default headers values
func NewCreateDurationDefault(code int) *CreateDurationDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateDurationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create duration default response
func (o *CreateDurationDefault) WithStatusCode(code int) *CreateDurationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create duration default response
func (o *CreateDurationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create duration default response
func (o *CreateDurationDefault) WithPayload(payload *models.Response) *CreateDurationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create duration default response
func (o *CreateDurationDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDurationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
