// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"boluswizard/models"
)

// NewCreateCorrectionsParams creates a new CreateCorrectionsParams object
//
// There are no default values defined in the spec.
func NewCreateCorrectionsParams() CreateCorrectionsParams {

	return CreateCorrectionsParams{}
}

// CreateCorrectionsParams contains all the bound params for the create corrections operation
// typically these are obtained from a http.Request
//
// swagger:parameters createCorrections
type CreateCorrectionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Corrections []*models.Correction
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateCorrectionsParams() beforehand.
func (o *CreateCorrectionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []*models.Correction
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("corrections", "body", ""))
			} else {
				res = append(res, errors.NewParseError("corrections", "body", "", err))
			}
		} else {

			// validate array of body objects
			for i := range body {
				if body[i] == nil {
					continue
				}
				if err := body[i].Validate(route.Formats); err != nil {
					res = append(res, err)
					break
				}
			}

			if len(res) == 0 {
				o.Corrections = body
			}
		}
	} else {
		res = append(res, errors.Required("corrections", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
