// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// CreateCorrectionsOKCode is the HTTP code returned for type CreateCorrectionsOK
const CreateCorrectionsOKCode int = 200

/*
CreateCorrectionsOK Successful operation

swagger:response createCorrectionsOK
*/
type CreateCorrectionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreateCorrectionsOK creates CreateCorrectionsOK with default headers values
func NewCreateCorrectionsOK() *CreateCorrectionsOK {

	return &CreateCorrectionsOK{}
}

// WithPayload adds the payload to the create corrections o k response
func (o *CreateCorrectionsOK) WithPayload(payload *models.Response) *CreateCorrectionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create corrections o k response
func (o *CreateCorrectionsOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCorrectionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CreateCorrectionsDefault Unsuccessful operation

swagger:response createCorrectionsDefault
*/
type CreateCorrectionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreateCorrectionsDefault creates CreateCorrectionsDefault with default headers values
func NewCreateCorrectionsDefault(code int) *CreateCorrectionsDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateCorrectionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create corrections default response
func (o *CreateCorrectionsDefault) WithStatusCode(code int) *CreateCorrectionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create corrections default response
func (o *CreateCorrectionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create corrections default response
func (o *CreateCorrectionsDefault) WithPayload(payload *models.Response) *CreateCorrectionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create corrections default response
func (o *CreateCorrectionsDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCorrectionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
