// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// CreateISFsOKCode is the HTTP code returned for type CreateISFsOK
const CreateISFsOKCode int = 200

/*
CreateISFsOK Successful operation

swagger:response createISFsOK
*/
type CreateISFsOK struct {

	/*
	  In: Body
	*/
	Payload *CreateISFsOKBody `json:"body,omitempty"`
}

// NewCreateISFsOK creates CreateISFsOK with default headers values
func NewCreateISFsOK() *CreateISFsOK {

	return &CreateISFsOK{}
}

// WithPayload adds the payload to the create i s fs o k response
func (o *CreateISFsOK) WithPayload(payload *CreateISFsOKBody) *CreateISFsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create i s fs o k response
func (o *CreateISFsOK) SetPayload(payload *CreateISFsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateISFsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CreateISFsDefault Unsuccessful operation

swagger:response createISFsDefault
*/
type CreateISFsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreateISFsDefault creates CreateISFsDefault with default headers values
func NewCreateISFsDefault(code int) *CreateISFsDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateISFsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create i s fs default response
func (o *CreateISFsDefault) WithStatusCode(code int) *CreateISFsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create i s fs default response
func (o *CreateISFsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create i s fs default response
func (o *CreateISFsDefault) WithPayload(payload *models.Response) *CreateISFsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create i s fs default response
func (o *CreateISFsDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateISFsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
