// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// GetISFsOKCode is the HTTP code returned for type GetISFsOK
const GetISFsOKCode int = 200

/*
GetISFsOK Successful operation

swagger:response getISFsOK
*/
type GetISFsOK struct {

	/*
	  In: Body
	*/
	Payload *GetISFsOKBody `json:"body,omitempty"`
}

// NewGetISFsOK creates GetISFsOK with default headers values
func NewGetISFsOK() *GetISFsOK {

	return &GetISFsOK{}
}

// WithPayload adds the payload to the get i s fs o k response
func (o *GetISFsOK) WithPayload(payload *GetISFsOKBody) *GetISFsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get i s fs o k response
func (o *GetISFsOK) SetPayload(payload *GetISFsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetISFsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetISFsDefault Unsuccessful operation

swagger:response getISFsDefault
*/
type GetISFsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetISFsDefault creates GetISFsDefault with default headers values
func NewGetISFsDefault(code int) *GetISFsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetISFsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get i s fs default response
func (o *GetISFsDefault) WithStatusCode(code int) *GetISFsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get i s fs default response
func (o *GetISFsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get i s fs default response
func (o *GetISFsDefault) WithPayload(payload *models.Response) *GetISFsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get i s fs default response
func (o *GetISFsDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetISFsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
