// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// GetCorrectionsOKCode is the HTTP code returned for type GetCorrectionsOK
const GetCorrectionsOKCode int = 200

/*
GetCorrectionsOK Successful operation

swagger:response getCorrectionsOK
*/
type GetCorrectionsOK struct {

	/*
	  In: Body
	*/
	Payload *GetCorrectionsOKBody `json:"body,omitempty"`
}

// NewGetCorrectionsOK creates GetCorrectionsOK with default headers values
func NewGetCorrectionsOK() *GetCorrectionsOK {

	return &GetCorrectionsOK{}
}

// WithPayload adds the payload to the get corrections o k response
func (o *GetCorrectionsOK) WithPayload(payload *GetCorrectionsOKBody) *GetCorrectionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get corrections o k response
func (o *GetCorrectionsOK) SetPayload(payload *GetCorrectionsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCorrectionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetCorrectionsDefault Unsuccessful operation

swagger:response getCorrectionsDefault
*/
type GetCorrectionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetCorrectionsDefault creates GetCorrectionsDefault with default headers values
func NewGetCorrectionsDefault(code int) *GetCorrectionsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCorrectionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get corrections default response
func (o *GetCorrectionsDefault) WithStatusCode(code int) *GetCorrectionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get corrections default response
func (o *GetCorrectionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get corrections default response
func (o *GetCorrectionsDefault) WithPayload(payload *models.Response) *GetCorrectionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get corrections default response
func (o *GetCorrectionsDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCorrectionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
