// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetDurationHandlerFunc turns a function with the right signature into a get duration handler
type GetDurationHandlerFunc func(GetDurationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDurationHandlerFunc) Handle(params GetDurationParams) middleware.Responder {
	return fn(params)
}

// GetDurationHandler interface for that can handle valid get duration params
type GetDurationHandler interface {
	Handle(GetDurationParams) middleware.Responder
}

// NewGetDuration creates a new http.Handler for the get duration operation
func NewGetDuration(ctx *middleware.Context, handler GetDurationHandler) *GetDuration {
	return &GetDuration{Context: ctx, Handler: handler}
}

/*
	GetDuration swagger:route GET /wizard/Duration getDuration

Get Duration
*/
type GetDuration struct {
	Context *middleware.Context
	Handler GetDurationHandler
}

func (o *GetDuration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDurationParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetDurationOKBody get duration o k body
//
// swagger:model GetDurationOKBody
type GetDurationOKBody struct {

	// data
	Data string `json:"Data,omitempty"`

	// error
	Error interface{} `json:"Error,omitempty"`

	// status
	Status int64 `json:"Status,omitempty"`
}

// Validate validates this get duration o k body
func (o *GetDurationOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get duration o k body based on context it is used
func (o *GetDurationOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetDurationOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDurationOKBody) UnmarshalBinary(b []byte) error {
	var res GetDurationOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
