// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// GetTargetsOKCode is the HTTP code returned for type GetTargetsOK
const GetTargetsOKCode int = 200

/*
GetTargetsOK Successful operation

swagger:response getTargetsOK
*/
type GetTargetsOK struct {

	/*
	  In: Body
	*/
	Payload *GetTargetsOKBody `json:"body,omitempty"`
}

// NewGetTargetsOK creates GetTargetsOK with default headers values
func NewGetTargetsOK() *GetTargetsOK {

	return &GetTargetsOK{}
}

// WithPayload adds the payload to the get targets o k response
func (o *GetTargetsOK) WithPayload(payload *GetTargetsOKBody) *GetTargetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get targets o k response
func (o *GetTargetsOK) SetPayload(payload *GetTargetsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTargetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetTargetsDefault Unsuccessful operation

swagger:response getTargetsDefault
*/
type GetTargetsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetTargetsDefault creates GetTargetsDefault with default headers values
func NewGetTargetsDefault(code int) *GetTargetsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTargetsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get targets default response
func (o *GetTargetsDefault) WithStatusCode(code int) *GetTargetsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get targets default response
func (o *GetTargetsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get targets default response
func (o *GetTargetsDefault) WithPayload(payload *models.Response) *GetTargetsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get targets default response
func (o *GetTargetsDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTargetsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
