// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// GetDurationOKCode is the HTTP code returned for type GetDurationOK
const GetDurationOKCode int = 200

/*
GetDurationOK Successful operation

swagger:response getDurationOK
*/
type GetDurationOK struct {

	/*
	  In: Body
	*/
	Payload *GetDurationOKBody `json:"body,omitempty"`
}

// NewGetDurationOK creates GetDurationOK with default headers values
func NewGetDurationOK() *GetDurationOK {

	return &GetDurationOK{}
}

// WithPayload adds the payload to the get duration o k response
func (o *GetDurationOK) WithPayload(payload *GetDurationOKBody) *GetDurationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get duration o k response
func (o *GetDurationOK) SetPayload(payload *GetDurationOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDurationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetDurationDefault Unsuccessful operation

swagger:response getDurationDefault
*/
type GetDurationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetDurationDefault creates GetDurationDefault with default headers values
func NewGetDurationDefault(code int) *GetDurationDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDurationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get duration default response
func (o *GetDurationDefault) WithStatusCode(code int) *GetDurationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get duration default response
func (o *GetDurationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get duration default response
func (o *GetDurationDefault) WithPayload(payload *models.Response) *GetDurationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get duration default response
func (o *GetDurationDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDurationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
