// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"boluswizard/models"
)

// NewCorrectionHandlerFunc turns a function with the right signature into a new correction handler
type NewCorrectionHandlerFunc func(NewCorrectionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NewCorrectionHandlerFunc) Handle(params NewCorrectionParams) middleware.Responder {
	return fn(params)
}

// NewCorrectionHandler interface for that can handle valid new correction params
type NewCorrectionHandler interface {
	Handle(NewCorrectionParams) middleware.Responder
}

// NewNewCorrection creates a new http.Handler for the new correction operation
func NewNewCorrection(ctx *middleware.Context, handler NewCorrectionHandler) *NewCorrection {
	return &NewCorrection{Context: ctx, Handler: handler}
}

/*
	NewCorrection swagger:route GET /wizard/NewCorrection newCorrection

New Correction
*/
type NewCorrection struct {
	Context *middleware.Context
	Handler NewCorrectionHandler
}

func (o *NewCorrection) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNewCorrectionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// NewCorrectionOKBody new correction o k body
//
// swagger:model NewCorrectionOKBody
type NewCorrectionOKBody struct {

	// data
	Data *models.CorrectionResponse `json:"Data,omitempty"`

	// error
	Error interface{} `json:"Error,omitempty"`

	// status
	Status int64 `json:"Status,omitempty"`
}

// Validate validates this new correction o k body
func (o *NewCorrectionOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NewCorrectionOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("newCorrectionOK" + "." + "Data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("newCorrectionOK" + "." + "Data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this new correction o k body based on the context it is used
func (o *NewCorrectionOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NewCorrectionOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("newCorrectionOK" + "." + "Data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("newCorrectionOK" + "." + "Data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *NewCorrectionOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *NewCorrectionOKBody) UnmarshalBinary(b []byte) error {
	var res NewCorrectionOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
