// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// NewCorrectionOKCode is the HTTP code returned for type NewCorrectionOK
const NewCorrectionOKCode int = 200

/*
NewCorrectionOK Successful operation

swagger:response newCorrectionOK
*/
type NewCorrectionOK struct {

	/*
	  In: Body
	*/
	Payload *NewCorrectionOKBody `json:"body,omitempty"`
}

// NewNewCorrectionOK creates NewCorrectionOK with default headers values
func NewNewCorrectionOK() *NewCorrectionOK {

	return &NewCorrectionOK{}
}

// WithPayload adds the payload to the new correction o k response
func (o *NewCorrectionOK) WithPayload(payload *NewCorrectionOKBody) *NewCorrectionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new correction o k response
func (o *NewCorrectionOK) SetPayload(payload *NewCorrectionOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewCorrectionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
NewCorrectionDefault Unsuccessful operation

swagger:response newCorrectionDefault
*/
type NewCorrectionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewNewCorrectionDefault creates NewCorrectionDefault with default headers values
func NewNewCorrectionDefault(code int) *NewCorrectionDefault {
	if code <= 0 {
		code = 500
	}

	return &NewCorrectionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the new correction default response
func (o *NewCorrectionDefault) WithStatusCode(code int) *NewCorrectionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the new correction default response
func (o *NewCorrectionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the new correction default response
func (o *NewCorrectionDefault) WithPayload(payload *models.Response) *NewCorrectionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new correction default response
func (o *NewCorrectionDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewCorrectionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
