// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewNewCorrectionParams creates a new NewCorrectionParams object
//
// There are no default values defined in the spec.
func NewNewCorrectionParams() NewCorrectionParams {

	return NewCorrectionParams{}
}

// NewCorrectionParams contains all the bound params for the new correction operation
// typically these are obtained from a http.Request
//
// swagger:parameters newCorrection
type NewCorrectionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	Bg float64
	/*
	  Required: true
	  In: query
	*/
	Carbs float64
	/*
	  Required: true
	  In: header
	*/
	AuthToken string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewNewCorrectionParams() beforehand.
func (o *NewCorrectionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qBg, qhkBg, _ := qs.GetOK("Bg")
	if err := o.bindBg(qBg, qhkBg, route.Formats); err != nil {
		res = append(res, err)
	}

	qCarbs, qhkCarbs, _ := qs.GetOK("Carbs")
	if err := o.bindCarbs(qCarbs, qhkCarbs, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindAuthToken(r.Header[http.CanonicalHeaderKey("authToken")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBg binds and validates parameter Bg from query.
func (o *NewCorrectionParams) bindBg(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Bg", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("Bg", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("Bg", "query", "float64", raw)
	}
	o.Bg = value

	return nil
}

// bindCarbs binds and validates parameter Carbs from query.
func (o *NewCorrectionParams) bindCarbs(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Carbs", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("Carbs", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("Carbs", "query", "float64", raw)
	}
	o.Carbs = value

	return nil
}

// bindAuthToken binds and validates parameter AuthToken from header.
func (o *NewCorrectionParams) bindAuthToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("authToken", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("authToken", "header", raw); err != nil {
		return err
	}
	o.AuthToken = raw

	return nil
}
