// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"boluswizard/models"
)

// SignUpOKCode is the HTTP code returned for type SignUpOK
const SignUpOKCode int = 200

/*
SignUpOK Successful operation

swagger:response signUpOK
*/
type SignUpOK struct {

	/*
	  In: Body
	*/
	Payload *SignUpOKBody `json:"body,omitempty"`
}

// NewSignUpOK creates SignUpOK with default headers values
func NewSignUpOK() *SignUpOK {

	return &SignUpOK{}
}

// WithPayload adds the payload to the sign up o k response
func (o *SignUpOK) WithPayload(payload *SignUpOKBody) *SignUpOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sign up o k response
func (o *SignUpOK) SetPayload(payload *SignUpOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignUpOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
SignUpDefault Unsuccessful operation

swagger:response signUpDefault
*/
type SignUpDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewSignUpDefault creates SignUpDefault with default headers values
func NewSignUpDefault(code int) *SignUpDefault {
	if code <= 0 {
		code = 500
	}

	return &SignUpDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the sign up default response
func (o *SignUpDefault) WithStatusCode(code int) *SignUpDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the sign up default response
func (o *SignUpDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the sign up default response
func (o *SignUpDefault) WithPayload(payload *models.Response) *SignUpDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sign up default response
func (o *SignUpDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignUpDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
