// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CarbRatio carb ratio
//
// swagger:model CarbRatio
type CarbRatio struct {

	// end
	End string `json:"End,omitempty"`

	// key
	Key string `json:"Key,omitempty"`

	// ratio
	Ratio float64 `json:"Ratio,omitempty"`

	// start
	Start string `json:"Start,omitempty"`
}

// Validate validates this carb ratio
func (m *CarbRatio) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this carb ratio based on context it is used
func (m *CarbRatio) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CarbRatio) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CarbRatio) UnmarshalBinary(b []byte) error {
	var res CarbRatio
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
