// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CorrectionResponse correction response
//
// swagger:model CorrectionResponse
type CorrectionResponse struct {

	// active insulin reduction
	ActiveInsulinReduction *float64 `json:"ActiveInsulinReduction,omitempty" redis:"ActiveInsulinReduction"`

	// bg correction
	BgCorrection *float64 `json:"BgCorrection,omitempty" redis:"BgCorrection"`

	// bolus
	Bolus *float64 `json:"Bolus,omitempty" redis:"Bolus"`

	// carb correction
	CarbCorrection *float64 `json:"CarbCorrection,omitempty" redis:"CarbCorrection"`
}

// Validate validates this correction response
func (m *CorrectionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this correction response based on context it is used
func (m *CorrectionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CorrectionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CorrectionResponse) UnmarshalBinary(b []byte) error {
	var res CorrectionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
