// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Sign sign
//
// swagger:model Sign
type Sign struct {

	// password
	Password string `json:"Password,omitempty"`

	// username
	Username string `json:"Username,omitempty"`
}

// Validate validates this sign
func (m *Sign) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sign based on context it is used
func (m *Sign) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Sign) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Sign) UnmarshalBinary(b []byte) error {
	var res Sign
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
