swagger: '2.0'
info:
  title: BolusWizard
  version: '1.0'

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

paths:
  /health:
    get:
      summary: Health Check
      operationId: healthCheck
      responses:
        200:
          description: Successful operation
          schema:
            allOf:
              - $ref: '#/definitions/Health'

  /wizard/Ratios:
    post:
      summary: Create Carb Ratios
      operationId: createRatios
      parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
        - name: carbRatios
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/CarbRatio'
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
                description: status code
              Error:
                type: object
                #nullable: true
              Data: 
                type: object
                #nullable: true
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'
    get:
      summary: Get Ratios
      operationId: getRatios
      #parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                type: array
                items: 
                  $ref: '#/definitions/CarbRatio'
                #nullable: false
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'
  /wizard/Targets:
    post:
      summary: Create Target Ratios
      operationId: createTargets
      parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
        - name: targetRatios
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Target'
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                type: object
                #nullable: true
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'
    get:
      summary: Get Targets
      operationId: getTargets
      #parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                type: array
                items: 
                  $ref: '#/definitions/Target'
                #nullable: false
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'
  /wizard/ISFs:
    post:
      summary: Create ISF
      operationId: createISFs
      parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
        - name: ISFs
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/ISF'
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                type: object
                #nullable: true
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'

    get:
      summary: Get ISFs
      operationId: getISFs
      #parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                type: array
                items: 
                  $ref: '#/definitions/ISF'
                #nullable: false
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'
  /wizard/Duration:
    post:
      summary: Create Duration
      operationId: createDuration
      parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
        - name: Duration
          in: body
          required: true
          schema:
            type: object
            properties:
              Duration:
                type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                type: object
                #nullable: true
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'

    get:
      summary: Get Duration
      operationId: getDuration
      #parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                type: string
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'

  /SignIn:
    post:
      summary: Sign In
      operationId: signIn
      parameters:
        - name: signInData
          in: body
          required: true
          schema:
            $ref: '#/definitions/Sign'
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                $ref: '#/definitions/Token'
                #nullable: false
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'
  
  /wizard/NewCorrection:
    get:
      summary: New Correction
      operationId: newCorrection
      parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
        - name: Bg
          in: query
          required: true
          type: number
          format: float64
        - name: Carbs
          in: query
          required: true
          type: number
          format: float64
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                $ref: '#/definitions/CorrectionResponse'
                #nullable: false
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'
  /wizard/CorrectionRange:
    get:
      summary: get correction range
      operationId: correctionRange
      parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
        - name: Start
          in: query
          required: true
          type: integer
          format: int64
        - name: End
          in: query
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                type: array
                items:
                  $ref: '#/definitions/Correction'
                #nullable: false
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'

  /SignUp:
    post:
      summary: Sign Up
      operationId: signUp
      parameters:
        - name: signUpData
          in: body
          required: true
          schema:
            $ref: '#/definitions/Sign'
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                $ref: '#/definitions/Token'
                #nullable: false
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'

  /wizard/corrections:
    post:
      summary: Create Corrections
      operationId: createCorrections
      parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
        - name: corrections
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Correction'
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/Response'
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'

    get:
      summary: Get Corrections
      operationId: getCorrections
      #parameters:
        # - name: wizardToken
        #   in: header
        #   required: true
        #   type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              Status:
                type: integer
              Error:
                type: object
                #nullable: true
              Data: 
                type: array
                items: 
                  $ref: '#/definitions/Correction' #change to corrections
                #nullable: false
        default:
          description: Unsuccessful operation
          schema:
            $ref: '#/definitions/Response'

definitions:
  CarbRatio:
    type: object
    properties:
      Key:
        type: string
        x-go-custom-tag: redis:"Key"
        x-nullable: true
      End:
        type: string
        x-go-custom-tag: redis:"End"
        x-nullable: true
      Start:
        type: string
        x-go-custom-tag: redis:"Start"
        x-nullable: true
      Ratio:
        type: number
        format: float64
        x-go-custom-tag: redis:"Ratio"
        x-nullable: true
  ISF:
    type: object
    properties:
      Key:
        type: string
        x-go-custom-tag: redis:"Key"
        x-nullable: true
      End:
        type: string
        x-go-custom-tag: redis:"End"
        x-nullable: true
      Start:
        type: string
        x-go-custom-tag: redis:"Start"
        x-nullable: true
      Sensitivity:
        type: number
        format: float64
        x-go-custom-tag: redis:"Sensitivity"
        x-nullable: true
  Target:
    type: object
    properties:
      Key:
        type: string
        x-go-custom-tag: redis:"Key"
        x-nullable: true
      End:
        type: string
        x-go-custom-tag: redis:"End"
        x-nullable: true
      Start:
        type: string
        x-go-custom-tag: redis:"Start"
        x-nullable: true
      High:
        type: number
        format: float64
        x-go-custom-tag: redis:"High"
        x-nullable: true
      low:
        type: number
        format: float64
        x-go-custom-tag: redis:"low"
        x-nullable: true
      Ratio:
        type: number
        format: float64
        x-go-custom-tag: redis:"Ratio"
        x-nullable: true

  CorrectionResponse:
    type: object
    properties:
      BgCorrection:
        type: number
        format: float64
        x-go-custom-tag: redis:"BgCorrection"
        x-nullable: true
      CarbCorrection:
        type: number
        format: float64
        x-go-custom-tag: redis:"CarbCorrection"
        x-nullable: true
      ActiveInsulinReduction:
        type: number
        format: float64
        x-go-custom-tag: redis:"ActiveInsulinReduction"
        x-nullable: true
      Bolus:
        type: number
        format: float64
        x-go-custom-tag: redis:"Bolus"
        x-nullable: true

  Sign:
    type: object
    properties:
      Username:
        type: string
        x-go-custom-tag: redis:"Username"
      Password:
        type: string
        x-go-custom-tag: redis:"Password"
  Users:
    type: object
    properties:
      Uid:
        type: string
        x-go-custom-tag: redis:"Uid"
      Username:
        type: string
        x-go-custom-tag: redis:"Username"
      Password:
        type: string
        x-go-custom-tag: redis:"Password"
  Token:
    type: object
    properties:
      Username:
        type: string
        x-go-custom-tag: redis:"Username"
      Token:
        type: string
        x-go-custom-tag: redis:"Token"
  ActiveInsulinDuration:
    type: object
    properties:
      Duration:
        type: string
        x-go-custom-tag: redis:"Duration"

  Correction:
    type: object
    properties:
      Key:
        type: string
      Bg:
        type: number
        format: float64
        x-go-custom-tag: redis:"Bg"
        x-nullable: true
      Carbs:
        type: number
        format: float64
        x-go-custom-tag: redis:"Carbs"
        x-nullable: true
      Bolus:
        type: number
        format: float64
        x-go-custom-tag: redis:"Bolus"
        x-nullable: true
      TimeStamp:
        type: integer
        format: int64
        x-go-custom-tag: redis:"TimeStamp"
        x-nullable: true
        
  Response:
    type: object
    properties:
      Status:
        type: integer
        x-nullable: true
      Error:
        type: object
        x-nullable: true
  CorrectionRange:
    type: object
    properties:
      Start:
        type: integer
        format: int64
        x-go-custom-tag: redis:"Start"
        x-nullable: true
      End:
        type: integer
        format: int64
        x-go-custom-tag: redis:"End"
        x-nullable: true

  ResponseData:
    type: object
    properties:
      Status:
        type: integer
      Error:
        type: object
      Data:
        type: object
  Health:
    type: object
    properties:
      Status:
        type: integer
      Error:
      x-nullable: true
        type: object
      Timestamp:
        type: object
