name: deploy to bwdev namespace
on:
  push:
    branches:
      - env/go

jobs:
  deploy:
    runs-on: [self-hosted, nated-8]
    needs: [ui,api]
    steps:
      - uses: actions/checkout@v3
      - id: get_version
        run: |
          echo "VERSION=$(cat ./VERSION)" >> $GITHUB_OUTPUT
      - name: Helm Deploy
        uses: 'deliverybot/helm@master'
        with:
          token: ${{ secrets.ALL_ACCESS_PAT }}
          release: ${{ steps.get_version.outputs.VERSION }}
          namespace: 'bwdev'
          chart: 'charts'
          value-files: >-
            [
              "../../charts/dev.yaml"
            ]
          values: |
            VERSION: ${{ steps.get_version.outputs.VERSION }}
        env: 
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
