name: production deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, nated-8]
    steps:
      - uses: actions/checkout@v3
      - id: get_version
        run: |
          echo "VERSION=$(cat ./VERSION)" >> $GITHUB_OUTPUT
      - name: Helm Deploy
        uses: vimeda/helm@v1.6.8
        with:
          token: ${{ secrets.ALL_ACCESS_PAT }}
          release: ${{ steps.get_version.outputs.VERSION }}
          namespace: 'bw'
          chart: 'charts'
          value-files: >-
            [
              "charts/prod.yaml"
            ]
          values: |
            VERSION: ${{ steps.get_version.outputs.VERSION }}
            TLS_CRT: ${{ secrets.TLS_CRT }}
            TLS_KEY: ${{ secrets.TLS_KEY }}
        env: 
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'